"""new

Revision ID: 0f1464bf978d
Revises: ff61f8d94026
Create Date: 2024-03-12 17:21:00.008195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f1464bf978d'
down_revision: Union[str, None] = 'ff61f8d94026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('is_corresponding', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authors', 'is_corresponding')
    # ### end Alembic commands ###
