"""new

Revision ID: 10a15a74ee91
Revises: c09409653d46
Create Date: 2024-03-18 13:45:09.364115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10a15a74ee91'
down_revision: Union[str, None] = 'c09409653d46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conferences', sa.Column('submission_deadline', sa.DateTime(timezone=True), nullable=True))
    op.add_column('conferences', sa.Column('start_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conferences', 'start_date')
    op.drop_column('conferences', 'submission_deadline')
    # ### end Alembic commands ###
