"""conference

Revision ID: 12f0739bdc04
Revises: cc4f15d78e29
Create Date: 2024-02-28 18:35:16.650779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12f0739bdc04'
down_revision: Union[str, None] = 'cc4f15d78e29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviewer_to_conference',
    sa.Column('conference_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conference_id'], ['conferences.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('conference_id', 'reviewer_id')
    )
    op.drop_table('user_to_conference')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_to_conference',
    sa.Column('conference_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reviewer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['conference_id'], ['conferences.id'], name='user_to_conference_conference_id_fkey'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name='user_to_conference_reviewer_id_fkey'),
    sa.PrimaryKeyConstraint('conference_id', 'reviewer_id', name='user_to_conference_pkey')
    )
    op.drop_table('reviewer_to_conference')
    # ### end Alembic commands ###
