"""conference

Revision ID: 172382db4933
Revises: 7a0ed255a240
Create Date: 2024-02-22 16:23:21.017780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '172382db4933'
down_revision: Union[str, None] = '7a0ed255a240'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('authors_submission_id_fkey', 'authors', type_='foreignkey')
    op.create_foreign_key(None, 'authors', 'submissions', ['submission_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'authors', type_='foreignkey')
    op.create_foreign_key('authors_submission_id_fkey', 'authors', 'conferences', ['submission_id'], ['id'])
    # ### end Alembic commands ###
