"""new

Revision ID: 28ccc481d5e9
Revises: dd7641160544
Create Date: 2024-03-07 03:54:55.742294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28ccc481d5e9'
down_revision: Union[str, None] = 'dd7641160544'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('category', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'category')
    # ### end Alembic commands ###
