"""new

Revision ID: 31bd938a7da3
Revises: c2738786894b
Create Date: 2024-03-19 16:33:01.072009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31bd938a7da3'
down_revision: Union[str, None] = 'c2738786894b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conferences', sa.Column('name_ru_dative', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conferences', 'name_ru_dative')
    # ### end Alembic commands ###
