"""new

Revision ID: 3c6fcc528a3f
Revises: 74c948e57b45
Create Date: 2024-04-08 19:09:05.911812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c6fcc528a3f'
down_revision: Union[str, None] = '74c948e57b45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('name_ru', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'name_ru')
    # ### end Alembic commands ###
