"""new

Revision ID: 476a5361fef2
Revises: 8e8e256d312e
Create Date: 2024-04-08 19:39:58.073650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '476a5361fef2'
down_revision: Union[str, None] = '8e8e256d312e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('category_ru', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'category_ru')
    # ### end Alembic commands ###
