"""conference

Revision ID: 69419837c55c
Revises: b63759832af0
Create Date: 2024-02-19 20:06:10.529011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69419837c55c'
down_revision: Union[str, None] = 'b63759832af0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'conferences', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conferences', type_='unique')
    # ### end Alembic commands ###
