"""new

Revision ID: 74c948e57b45
Revises: 6ad9424595ac
Create Date: 2024-04-03 12:37:22.345446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74c948e57b45'
down_revision: Union[str, None] = '6ad9424595ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conferences', sa.Column('email', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conferences', 'email')
    # ### end Alembic commands ###
