"""new

Revision ID: 80d493deb8e1
Revises: 10a15a74ee91
Create Date: 2024-03-18 14:12:03.703587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80d493deb8e1'
down_revision: Union[str, None] = '10a15a74ee91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('orcid_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'orcid_id')
    # ### end Alembic commands ###
