"""new

Revision ID: a2338e27af9d
Revises: dfe6ec42f8e8
Create Date: 2024-03-07 06:36:08.134173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2338e27af9d'
down_revision: Union[str, None] = 'dfe6ec42f8e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('is_ru', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'is_ru')
    # ### end Alembic commands ###
