"""topic_id

Revision ID: b48cc8bea73d
Revises: db3b16ec9d59
Create Date: 2024-04-10 22:50:26.336458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b48cc8bea73d'
down_revision: Union[str, None] = 'db3b16ec9d59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chair_to_conference',
    sa.Column('conference_id', sa.Integer(), nullable=False),
    sa.Column('chair_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chair_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['conference_id'], ['conferences.id'], ),
    sa.PrimaryKeyConstraint('conference_id', 'chair_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chair_to_conference')
    # ### end Alembic commands ###
