"""new

Revision ID: b71151347d71
Revises: 66b42f20ff49
Create Date: 2024-03-07 06:56:41.063146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b71151347d71'
down_revision: Union[str, None] = '66b42f20ff49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conferences', sa.Column('acronym', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'conferences', ['acronym'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conferences', type_='unique')
    op.drop_column('conferences', 'acronym')
    # ### end Alembic commands ###
