"""new

Revision ID: c2738786894b
Revises: fbdd50e15f2f
Create Date: 2024-03-18 15:16:16.565298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2738786894b'
down_revision: Union[str, None] = 'fbdd50e15f2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conferences', sa.Column('short_name', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'conferences', ['short_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conferences', type_='unique')
    op.drop_column('conferences', 'short_name')
    # ### end Alembic commands ###
