"""new

Revision ID: c5167dd4dfc9
Revises: ecdbbe15c78d
Create Date: 2024-03-07 05:13:56.273299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5167dd4dfc9'
down_revision: Union[str, None] = 'ecdbbe15c78d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('title_ru', sa.Text(), nullable=True))
    op.add_column('submissions', sa.Column('abstract_ru', sa.Text(), nullable=True))
    op.add_column('submissions', sa.Column('keywords_ru', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'keywords_ru')
    op.drop_column('submissions', 'abstract_ru')
    op.drop_column('submissions', 'title_ru')
    # ### end Alembic commands ###
