"""new

Revision ID: dd7641160544
Revises: 12f0739bdc04
Create Date: 2024-03-07 03:41:21.071482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd7641160544'
down_revision: Union[str, None] = '12f0739bdc04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conferences', sa.Column('site_url', sa.Text(), nullable=True))
    op.add_column('conferences', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conferences', 'description')
    op.drop_column('conferences', 'site_url')
    # ### end Alembic commands ###
