"""new

Revision ID: dfe6ec42f8e8
Revises: c5167dd4dfc9
Create Date: 2024-03-07 05:31:21.453723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfe6ec42f8e8'
down_revision: Union[str, None] = 'c5167dd4dfc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'title')
    # ### end Alembic commands ###
