"""new

Revision ID: ecdbbe15c78d
Revises: 28ccc481d5e9
Create Date: 2024-03-07 04:02:59.329264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecdbbe15c78d'
down_revision: Union[str, None] = '28ccc481d5e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conferences', sa.Column('allow_ru', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conferences', 'allow_ru')
    # ### end Alembic commands ###
