"""conference

Revision ID: f85c1069f439
Revises: bbf671306141
Create Date: 2024-02-21 18:22:10.510847

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f85c1069f439"
down_revision: Union[str, None] = "bbf671306141"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "submissions",
        "approved",
        existing_type=sa.TEXT(),
        type_=sa.Boolean(),
        postgresql_using="approved::boolean",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "submissions",
        "approved",
        existing_type=sa.Boolean(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
